// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayConfig
{
        public const string achievement_beelzebub = "CgkIgvyVhp0OEAIQEQ"; // <GPGSID>
        public const string achievement_hell_cartographer = "CgkIgvyVhp0OEAIQGw"; // <GPGSID>
        public const string achievement_phenomenal = "CgkIgvyVhp0OEAIQDw"; // <GPGSID>
        public const string achievement_tempted = "CgkIgvyVhp0OEAIQGg"; // <GPGSID>
        public const string achievement_ordinary_one = "CgkIgvyVhp0OEAIQBg"; // <GPGSID>
        public const string achievement_talented = "CgkIgvyVhp0OEAIQCA"; // <GPGSID>
        public const string leaderboard_normal = "CgkIgvyVhp0OEAIQAg"; // <GPGSID>
        public const string leaderboard_devil = "CgkIgvyVhp0OEAIQAQ"; // <GPGSID>
        public const string achievement_devoted_to_relaxing = "CgkIgvyVhp0OEAIQFQ"; // <GPGSID>
        public const string achievement_lopts_friend = "CgkIgvyVhp0OEAIQHg"; // <GPGSID>
        public const string leaderboard_relax = "CgkIgvyVhp0OEAIQAw"; // <GPGSID>
        public const string achievement_first_time_relaxing = "CgkIgvyVhp0OEAIQBQ"; // <GPGSID>
        public const string achievement_first_sin = "CgkIgvyVhp0OEAIQBw"; // <GPGSID>
        public const string achievement_patient = "CgkIgvyVhp0OEAIQCg"; // <GPGSID>
        public const string achievement_fealty = "CgkIgvyVhp0OEAIQHA"; // <GPGSID>
        public const string achievement_tranquil = "CgkIgvyVhp0OEAIQFg"; // <GPGSID>
        public const string achievement_playing_with_fire = "CgkIgvyVhp0OEAIQGQ"; // <GPGSID>
        public const string achievement_mefistofeles = "CgkIgvyVhp0OEAIQEg"; // <GPGSID>
        public const string achievement_epic = "CgkIgvyVhp0OEAIQDg"; // <GPGSID>
        public const string achievement_lopts_favourite = "CgkIgvyVhp0OEAIQHw"; // <GPGSID>
        public const string achievement_curious = "CgkIgvyVhp0OEAIQGA"; // <GPGSID>
        public const string achievement_loyal = "CgkIgvyVhp0OEAIQHQ"; // <GPGSID>
        public const string achievement_disciple = "CgkIgvyVhp0OEAIQBA"; // <GPGSID>
        public const string achievement_chiller = "CgkIgvyVhp0OEAIQCQ"; // <GPGSID>
        public const string achievement_leviathan = "CgkIgvyVhp0OEAIQEw"; // <GPGSID>
        public const string achievement_extraordinary = "CgkIgvyVhp0OEAIQDA"; // <GPGSID>
        public const string achievement_lucifer = "CgkIgvyVhp0OEAIQEA"; // <GPGSID>
        public const string achievement_stoic = "CgkIgvyVhp0OEAIQFw"; // <GPGSID>
        public const string achievement_enjoying_relaxing = "CgkIgvyVhp0OEAIQFA"; // <GPGSID>
        public const string achievement_nolife = "CgkIgvyVhp0OEAIQCw"; // <GPGSID>
        public const string achievement_rare = "CgkIgvyVhp0OEAIQDQ"; // <GPGSID>

}

